import 'package:flutter/material.dart';
import 'package:hive/hive.dart';
import '../models/backpack_item.dart';
import '../models/course_schedule.dart';
import '../utils/date_utils.dart';

/// 没有课本的活动类科目，不自动生成书包物品
const Set<String> _noBookSubjects = {
  '快乐活动',
  '课后服务',
  '综合活动',
  '体活',
  '自习',
};

/// 书包管理 Provider
class BackpackProvider extends ChangeNotifier {
  final Box<BackpackItem> _box = Hive.box<BackpackItem>('backpackItems');
  final Box _settingsBox = Hive.box('settings');

  List<BackpackItem> _backpackItems = [];

  List<BackpackItem> get backpackItems => _backpackItems;

  /// 初始化：从 Hive 读取数据
  BackpackProvider() {
    _loadFromBox();
  }

  void _loadFromBox() {
    _backpackItems = _box.values.toList();
    notifyListeners();
  }

  /// 获取指定学生的书包物品
  List<BackpackItem> getItemsForStudent(String studentId) {
    return _backpackItems.where((i) => i.studentId == studentId).toList();
  }

  /// 获取指定日期的书包物品
  List<BackpackItem> getItemsForDay(String studentId, int dayOfWeek, DateTime date) {
    return _backpackItems.where((i) =>
      i.studentId == studentId &&
      (i.isRecurring && i.relatedDayOfWeek == dayOfWeek ||
       !i.isRecurring && i.specificDate != null &&
       i.specificDate!.year == date.year &&
       i.specificDate!.month == date.month &&
       i.specificDate!.day == date.day)
    ).toList();
  }

  /// 获取用户已忽略的自动生成物品 ID 列表
  Set<String> _getDismissedIds(String studentId) {
    final raw = _settingsBox.get('dismissedAutoItems_$studentId', defaultValue: <String>[]);
    if (raw is List) return raw.toSet().cast<String>();
    return {};
  }

  /// 记录用户已忽略的自动生成物品
  void _dismissAutoItem(String studentId, String itemId) {
    final dismissed = _getDismissedIds(studentId).toList();
    dismissed.add(itemId);
    _settingsBox.put('dismissedAutoItems_$studentId', dismissed);
  }

  /// 基于明天课表自动生成书包建议
  void generateSuggestionsForTomorrow(String studentId, String semesterId, List<CourseSchedule> schedules) {
    final tomorrowDayOfWeek = getTomorrowDayOfWeek();

    // 仅周一到周五生成
    if (tomorrowDayOfWeek > 5) return;

    final tomorrowSchedules = schedules.where((s) =>
      s.studentId == studentId &&
      s.semesterId == semesterId &&
      s.dayOfWeek == tomorrowDayOfWeek
    ).toList();

    // 获取用户已忽略的自动生成项
    final dismissedIds = _getDismissedIds(studentId);

    // 为每个科目生成默认书包物品（跳过活动类科目和已忽略项）
    for (final schedule in tomorrowSchedules) {
      final subject = schedule.subject;

      // 跳过没有课本的活动类科目
      if (_noBookSubjects.contains(subject)) continue;

      final autoId = '${studentId}_${tomorrowDayOfWeek}_${subject}';

      // 跳过用户已手动删除的
      if (dismissedIds.contains(autoId)) continue;

      final existingItem = _backpackItems.where((i) =>
        i.studentId == studentId &&
        i.isAutoGenerated &&
        i.isRecurring &&
        i.relatedSubject == subject &&
        i.relatedDayOfWeek == tomorrowDayOfWeek
      ).firstOrNull;

      if (existingItem == null) {
        final itemName = '${subject}课本/练习册';
        final item = BackpackItem(
          id: autoId,
          studentId: studentId,
          itemName: itemName,
          relatedSubject: subject,
          relatedDayOfWeek: tomorrowDayOfWeek,
          isRecurring: true,
          isPacked: false,
          isAutoGenerated: true,
        );
        _box.put(item.id, item);
      }
    }

    _backpackItems = _box.values.toList();
    notifyListeners();
  }

  /// 切换已装入状态
  void togglePacked(String id) {
    final item = _backpackItems.where((i) => i.id == id).firstOrNull;
    if (item != null) {
      item.isPacked = !item.isPacked;
      item.save();
      _backpackItems = _box.values.toList();
      notifyListeners();
    }
  }

  /// 手动添加书包物品
  void addManualItem(BackpackItem item) {
    _box.put(item.id, item);
    _backpackItems = _box.values.toList();
    notifyListeners();
  }

  /// 删除书包物品
  void deleteItem(String id) {
    final item = _backpackItems.where((i) => i.id == id).firstOrNull;
    if (item != null && item.isAutoGenerated) {
      // 记录用户已忽略的自动生成物品（下次不再自动生成）
      _dismissAutoItem(item.studentId, id);
    }
    _box.delete(id);
    _backpackItems = _box.values.toList();
    notifyListeners();
  }

  /// 重置所有书包物品的打包状态（用于新的一天）
  void resetPackedStatus(String studentId) {
    for (final item in _backpackItems) {
      if (item.studentId == studentId) {
        item.isPacked = false;
        item.save();
      }
    }
    _backpackItems = _box.values.toList();
    notifyListeners();
  }
}
