// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'backpack_item.dart';

// **************************************************************************
// TypeAdapterGenerator
// **************************************************************************

class BackpackItemAdapter extends TypeAdapter<BackpackItem> {
  @override
  final int typeId = 7;

  @override
  BackpackItem read(BinaryReader reader) {
    final numOfFields = reader.readByte();
    final fields = <int, dynamic>{
      for (int i = 0; i < numOfFields; i++) reader.readByte(): reader.read(),
    };
    return BackpackItem(
      id: fields[0] as String,
      studentId: fields[1] as String,
      itemName: fields[2] as String,
      relatedSubject: fields[3] as String,
      relatedDayOfWeek: fields[4] as int,
      isRecurring: fields[5] as bool,
      specificDate: fields[6] as DateTime?,
      isPacked: fields[7] as bool,
      isAutoGenerated: fields[8] as bool,
    );
  }

  @override
  void write(BinaryWriter writer, BackpackItem obj) {
    writer
      ..writeByte(9)
      ..writeByte(0)
      ..write(obj.id)
      ..writeByte(1)
      ..write(obj.studentId)
      ..writeByte(2)
      ..write(obj.itemName)
      ..writeByte(3)
      ..write(obj.relatedSubject)
      ..writeByte(4)
      ..write(obj.relatedDayOfWeek)
      ..writeByte(5)
      ..write(obj.isRecurring)
      ..writeByte(6)
      ..write(obj.specificDate)
      ..writeByte(7)
      ..write(obj.isPacked)
      ..writeByte(8)
      ..write(obj.isAutoGenerated);
  }

  @override
  int get hashCode => typeId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BackpackItemAdapter &&
          runtimeType == other.runtimeType &&
          typeId == other.typeId;
}
