import 'package:hive/hive.dart';

part 'backpack_item.g.dart';

@HiveType(typeId: 7)
class BackpackItem extends HiveObject {
  @HiveField(0)
  String id;

  @HiveField(1)
  String studentId;

  @HiveField(2)
  String itemName;

  @HiveField(3)
  String relatedSubject;

  @HiveField(4)
  int relatedDayOfWeek; // 1-5

  @HiveField(5)
  bool isRecurring; // 是否每周重复

  @HiveField(6)
  DateTime? specificDate; // 特定日期（非重复时）

  @HiveField(7)
  bool isPacked; // 是否已装入书包

  @HiveField(8)
  bool isAutoGenerated; // 是否由课表自动生成

  BackpackItem({
    required this.id,
    required this.studentId,
    required this.itemName,
    this.relatedSubject = '',
    this.relatedDayOfWeek = 1,
    this.isRecurring = true,
    this.specificDate,
    this.isPacked = false,
    this.isAutoGenerated = false,
  });
}
