import 'package:flutter/material.dart';
import 'package:course_manager/theme/design_tokens.dart';
import 'package:course_manager/models/backpack_item.dart';

/// 书包物品行组件
/// 勾选框 + 物品名 + 科目标签 + 删除按钮

class BackpackItemRow extends StatelessWidget {
  final BackpackItem item;
  final VoidCallback onTogglePacked;
  final VoidCallback onDelete;

  const BackpackItemRow({
    super.key,
    required this.item,
    required this.onTogglePacked,
    required this.onDelete,
  });

  /// 获取科目对应的颜色
  Color _getSubjectColor(String subject) {
    return DesignTokens.subjectColors[subject] ?? DesignTokens.textAux2;
  }

  @override
  Widget build(BuildContext context) {
    final isPacked = item.isPacked;
    final hasSubject = item.relatedSubject.isNotEmpty;

    return Padding(
      padding: const EdgeInsets.symmetric(
        vertical: DesignTokens.elementGap / 2,
      ),
      child: Row(
        children: [
          // 勾选框
          GestureDetector(
            onTap: onTogglePacked,
            behavior: HitTestBehavior.opaque,
            child: isPacked
                ? Container(
                    width: 24,
                    height: 24,
                    decoration: BoxDecoration(
                      color: DesignTokens.accent,
                      shape: BoxShape.circle,
                    ),
                    child: const Icon(
                      Icons.check,
                      size: 16,
                      color: DesignTokens.card,
                    ),
                  )
                : Container(
                    width: 24,
                    height: 24,
                    decoration: BoxDecoration(
                      border: Border.all(
                        color: DesignTokens.textAux3,
                        width: 2,
                      ),
                      shape: BoxShape.circle,
                    ),
                  ),
          ),
          const SizedBox(width: DesignTokens.elementGapLarge),

          // 物品名 + 科目标签
          Expanded(
            child: Row(
              children: [
                // 物品名
                Flexible(
                  child: Text(
                    item.itemName,
                    style: TextStyle(
                      fontSize: DesignTokens.bodySize,
                      fontWeight: DesignTokens.bodyWeight,
                      color: isPacked
                          ? DesignTokens.textAux1
                          : DesignTokens.textPrimary,
                      decoration: isPacked
                          ? TextDecoration.lineThrough
                          : TextDecoration.none,
                    ),
                    overflow: TextOverflow.ellipsis,
                  ),
                ),

                // 科目标签
                if (hasSubject) ...[
                  const SizedBox(width: DesignTokens.elementGap),
                  Container(
                    padding: const EdgeInsets.symmetric(
                      horizontal: 6,
                      vertical: 2,
                    ),
                    decoration: BoxDecoration(
                      color: _getSubjectColor(item.relatedSubject)
                          .withValues(alpha: 0.15),
                      borderRadius: BorderRadius.circular(4),
                    ),
                    child: Text(
                      item.relatedSubject,
                      style: TextStyle(
                        fontSize: DesignTokens.tagSize,
                        fontWeight: DesignTokens.tagWeight,
                        color: _getSubjectColor(item.relatedSubject),
                      ),
                    ),
                  ),
                ],

                // 自动生成标签
                if (item.isAutoGenerated) ...[
                  const SizedBox(width: DesignTokens.elementGap / 2),
                  Container(
                    padding: const EdgeInsets.symmetric(
                      horizontal: 6,
                      vertical: 2,
                    ),
                    decoration: BoxDecoration(
                      color: DesignTokens.successBg,
                      borderRadius: BorderRadius.circular(4),
                    ),
                    child: const Text(
                      '自动',
                      style: TextStyle(
                        fontSize: DesignTokens.tagSize,
                        fontWeight: DesignTokens.tagWeight,
                        color: DesignTokens.textAux2,
                      ),
                    ),
                  ),
                ],
              ],
            ),
          ),

          const SizedBox(width: DesignTokens.elementGap),

          // 删除按钮
          GestureDetector(
            onTap: onDelete,
            behavior: HitTestBehavior.opaque,
            child: const Icon(
              Icons.close,
              size: 18,
              color: DesignTokens.textAux3,
            ),
          ),
        ],
      ),
    );
  }
}
